services:

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    env_file:
      - ../.env
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001

  postgres:
    image: postgres:17-alpine
    restart: always
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    env_file:
      - ../.env
    ports:
      - "5672:5672"  #  AMQP
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data

volumes:
  minio_data:
  postgres_data:
  rabbitmq_data: